version: '3'

services:
    db:
      image: mysql:5.6.50
      environment:
        MYSQL_ROOT_PASSWORD: password
      ports:
          - "4306:3306"
      volumes:
          - db-data:/var/lib/mysql
    app:
      build: .
      command: bundle exec puma -C config/puma.rb
      volumes:
        - .:/SAKELIKE
        - public-data:/SAKELIKE/public
        - tmp-data:/SAKELIKE/tmp
        - log-data:/SAKELIKE/log
      environment:
        BASIC_AUTH_USER: ${BASIC_AUTH_USER:-default}
        BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD-default}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-default}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-default}
    web:
        build:
          context: containers/nginx
        volumes:
          - public-data:/SAKELIKE/public
          - tmp-data:/SAKELIKE/tmp
        ports:
          - 8080:80
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

